In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [35]:
df = pd.read_csv("houseprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [36]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [38]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [39]:
df.shape

(5, 4)

In [41]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [42]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [44]:
reg.intercept_

383724.99999999994

In [45]:
reg.predict([[3000,3,40]])

array([444400.])

# Hiring Problem and Solution

In [53]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [56]:
d = pd.read_csv('hiring.csv')
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [62]:
d.experience = d.experience.fillna("zero")
d.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [63]:
d.experience = d.experience.apply(w2n.word_to_num)

In [64]:
d.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [66]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [67]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [74]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [78]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [79]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [80]:
reg.intercept_

14992.651446693148

In [81]:
reg.predict([[12,10,10]])

array([93747.79628651])